### ISSUE TITLE
강의 다운로드 창에 과목명 표시

### ISSUE THREAD

**Issue by xorud4277** [gusfhr777/Easy_Study#1]

**Comment by xorud4277** [comment]
노고에 감사드립니다. 해당 기능 추가되면 좋겠습니다!

**Comment by gusfhr777** [comment]
안녕하세요. 좋은 아이디어 같습니다. 추가하도록 하겠습니다.

**Comment by gusfhr777** [comment]
해당 기능을 업데이트 하였습니다. 과목을 누르면 해당 과목의 모든 영상 선택이 가능합니다.
